source :rubygems

gem 'rails', '~>3.0.5'
gem 'sqlite3-ruby', :require => 'sqlite3', :groups => ['test', 'development']

gem 'haml'
gem 'authlogic'
gem 'will_paginate'
gem 'sunspot'
gem 'sunspot_rails'
# gem 'nokogiri'
# gem 'feedzirra'
gem 'mysql'
# gem 'loofah'

group :test do
  gem 'rspec-rails', '= 2.5.0'
  gem 'database_cleaner', '~> 0.5.2'
  gem 'factory_girl_rails'
  gem 'factory_girl', '= 1.3.3'
  gem 'minitest'
  gem 'machinist'
  gem 'shoulda', :require => 'shoulda'
  gem 'mocha'
  gem 'ffaker'
  gem 'webrat'
  if RUBY_VERSION < "1.9"
    gem "ruby-debug"
  else
    gem "ruby-debug19"
  end
end

group :cucumber do
  gem 'cucumber-rails'
  gem 'database_cleaner', '~> 0.5.2'
  # gem 'nokogiri'
  gem 'capybara', '= 0.4.1.2'
  gem 'factory_girl_rails'
  gem 'factory_girl', '= 1.3.3'
  if RUBY_VERSION < "1.9"
    gem "ruby-debug"
  else
    gem "ruby-debug19"
  end
end
