# coding: utf-8

require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

desc 'Test the searchstorm_gather gem.'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/*_test.rb'
  test.verbose = true
end

desc 'Default: run unit tests.'
task :default => :test

desc "Regenerates a rails 3 app for testing"
task :test_app do
  require '../lib/generators/searchstorm/test_app_generator'
  class GatherTestAppGenerator < Searchstorm::Generators::TestAppGenerator

    def install_gems
      inside "test_app" do
        run 'rake searchstorm_core:install'
        run 'rake searchstorm_gather:install'
      end
    end

    def migrate_db
      run_migrations
    end

    protected
    def full_path_for_local_gems
      <<-gems
gem 'searchstorm_core', :path => \'#{File.join(File.dirname(__FILE__), "..", "core")}\'
gem 'searchstorm_gather', :path => \'#{File.join(File.dirname(__FILE__), "..", "gather")}\'
      gems
    end

  end
  GatherTestAppGenerator.start
end

desc 'Generate documentation for the searchstorm_gather gem.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "searchstorm #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

begin
  require 'rcov/rcovtask'
  Rcov::RcovTask.new do |test|
    test.libs << 'test'
    test.pattern = 'test/**/test_*.rb'
    test.verbose = true
  end
rescue LoadError
  task :rcov do
    abort "RCov is not available. In order to run rcov, you must: sudo gem install spicycode-rcov"
  end
end
