# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{searchstorm_gather}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gyorgy Frivolt"]
  s.date = %q{2011-04-17}
  s.description = %q{}
  s.email = %q{gyorgy.frivolt@gmail.com}
  s.files = [
    ".autotest",
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "install.rb",
    "lib/searchstorm_gather.rb",
    "lib/searchstorm_gather/tasks.rb",
    "lib/searchstorm_gather/tasks/gather.rake",
    "searchstorm_gather.gemspec",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fifigyuri/searchstorm}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Crawler extension for the searchstorm search-engine front-end}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<searchstorm_core>, ["~> 0.1.2"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.5"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.1"])
      s.add_runtime_dependency(%q<anemone>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, ["~> 2.11.1"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
    else
      s.add_dependency(%q<searchstorm_core>, ["~> 0.1.2"])
      s.add_dependency(%q<rails>, ["~> 3.0.5"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
      s.add_dependency(%q<anemone>, ["~> 0.5.0"])
      s.add_dependency(%q<mongo>, ["~> 1.2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.5.0"])
      s.add_dependency(%q<thoughtbot-shoulda>, ["~> 2.11.1"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
    end
  else
    s.add_dependency(%q<searchstorm_core>, ["~> 0.1.2"])
    s.add_dependency(%q<rails>, ["~> 3.0.5"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.1"])
    s.add_dependency(%q<anemone>, ["~> 0.5.0"])
    s.add_dependency(%q<mongo>, ["~> 1.2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.5.0"])
    s.add_dependency(%q<thoughtbot-shoulda>, ["~> 2.11.1"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
  end
end

